config/routes.rb
Rails.application.routes.draw do

  get 'messages' => 'messages#new'
  resources :messages
  root 'messages#new'
  post 'messages/api' => 'messages#api'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  #protect_from_forgery with: :exception
  protect_from_forgery with: :null_session
end

app/controllers/messages_controller.rb
require 'json'
require 'net/http'

class MessagesController < ApplicationController

  protect_from_forgery except: :api

  def new
  end
  def create
		@m=Message.new(params.require(:messages).permit(:text))
    @m.save
    url = "https://jubilant-meme.herokuapp.com/messages/" + @m.id.to_s
render plain: url
  end
  def show
		@m= Message.find(params[:id])
  end

  def api
    if request.headers["Content-Type"] == 'application/json'
      json = params.permit(:message)
  		@m = Message.new
  		@m.text = json.to_h[:message]
  		@m.save
      puts @m.text
  		url = "https://jubilant-meme.herokuapp.com/messages/" + @m.id.to_s
  		url_json = {:url => url}
      render json: url_json.to_json
    end

    if request.headers["Content-Type"] == 'text/xml'
      message_hash = Hash.from_xml(request.body.read)
      params[:message] = {"text" => message_hash["message"]}
      @m = Message.create(params.require(:message).permit(:text))
      url = {"url" => messages_url + "/" + @m.id.to_s}
      render :api
    end
  end

end

app/controllers/text_controller.rb
class TextController < ApplicationController
  def input
  end
  def creat
		@m=Message.new(params.require(:messages).permit(:text))
    @m.save
  end
  def output
		@m= Message.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/text_helper.rb
module TextHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hw2</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/messages/create.html.erb
<%= link_to message_path(@m), message_path(@m) %>

app/views/messages/new.html.erb
<%= form_with scope: :messages, local: true do |form| %>

  <%= form.text_area :text %>
  <%= submit_tag "submit", :name => nil, :id => "submit"%>
<% end %>

app/views/messages/show.html.erb
<%= @m.text %>

app/views/text/input.html.erb
<%= form_tag("/", :method => "get") do %>
  <%= text_area :post, :body, cols: 50, rows: 20 %>
  <%= submit_tag "submit", :name => nil, :id => "submit"%>
<% end %>